apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "default-psp.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "default-psp.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ toYaml .Values.clusterrolebinding.subjects | indent 2 }}
