{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels: {{- include "fluentd.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "fluentd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
