language: bash

services:
  - docker

env:
  global:
    - TEST_IMAGE="quay.io/helmpack/chart-testing:v3.0.0-rc.1"

script:
  - tests/run.sh

branches:
  only:
  - master

notifications:
  email: false
