apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "default-psp.fullname" . }}
  annotations:
{{ toYaml .Values.psp.annotations | indent 4 }}
  labels:
{{ include "default-psp.labels" . | indent 4 }}
spec:
{{ toYaml .Values.psp.spec | indent 2 }}
