apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.labels.serviceAccount }}
  labels:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.serviceAccount }}
  annotations:
    {{- with .Values.annotations.serviceAccount }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
