apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-ratelimit.fullname" . }}
  labels:
    {{- include "go-ratelimit.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2}}
