apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-ratelimit.fullname" . }}
  labels:
    {{- include "go-ratelimit.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.config | nindent 4 }}
