apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "telegraf.name" . }}
    helm.sh/chart: {{ include "telegraf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telegraf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telegraf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        args:
          - telegraf
          - --pidfile /pid/telegraf
        resources:
          {{- toYaml .Values.resources | indent 10 }}
        {{- if .Values.env }}
        env:
          {{- toYaml .Values.env | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: telegraf_config
          mountPath: /etc/telegraf
        - name: pid
          mountPath: /pid
      - name: consul-template
        image: "{{ .Values.consulTemplate.repo }}:{{ .Values.consulTemplate.tag }}"
        imagePullPolicy: {{ .Values.consulTemplate.pullPolicy }}
        resources:
          {{- toYaml .Values.consulTemplate.resources | nindent 10 }}
        env:
        - name: "HOST_IP"
          valueFrom:
            fieldRef:
              fieldPath: "status.hostIP"
        {{- if .Values.consulTemplate.env }}
        {{- toYaml .Values.consulTemplate.env | indent 8 }}
        {{- end }}
        volumeMounts:
        - name: telegraf_config
          mountPath: /etc/telegraf
        - name: ct
          mountPath: /ct
        - name: vault
          mountPath: /vault
        - name: pid
          mountPath: /pid
        command:
          - "/bin/consul-template"
        args:
          - "-consul-addr=$(HOST_IP):8500"
          - "-config=/ct/config.hcl"
          - "-log-level=debug"
        livenessProbe:
          exec:
            command:
            - cat
            - /pid/consul-template
          initialDelaySeconds: 10
      {{- if .Values.vaultAgent.enabled }}
        - name: vault-agent
          image: "{{ .Values.vault.repo }}:{{ .Values.vault.tag }}"
          imagePullPolicy: {{ .Values.vault.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/vault
                  - token
                  - revoke
                  - -self
          resources:
            {{- toYaml .Values.vaultAgent.resources | nindent 10 }}
          volumeMounts:
            - name: vault
              mountPath: /vault
              readOnly: true
            - name: pid
              mountPath: /pid
            {{- if .Values.vault.env }}
          env:
            {{- toYaml .Values.vault.env | nindent 10 }}
            {{- end }}
          command:
            - /bin/vault
          args:
            - agent
            - -config=/vault/agent.hcl
            - -log-level=debug
          livenessProbe:
            exec:
              command:
              - cat
              - /pid/vault-agent
              - /vault/token
initialDelaySeconds: 10
      {{- end }}
      volumes:
      - name: telegraf_config
        emptyDir: {}
      - name: pid
        emptyDir: {}
      - name: ct
        configMap:
          name: {{ include "telegraf.fullname" . }}-ct
      - name: vault
        configMap:
          name: {{ include "telegraf.fullname" . }}-vault
      - name: tpl
        configMap:
          name: {{ include "telegraf.fullname" . }}-tpl
