# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule
schedule: "0 3 * * *"
# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
concurrencyPolicy: "Allow"

successfulJobsHistoryLimit: "10"
failedJobsHistoryLimit: "10"

ttlSecondsAfterFinished: 86400

image:
  repository: basisai/consul-backup-gcs
  tag: 0.3.2
  pullPolicy: IfNotPresent

env: []

nameOverride: ""
fullnameOverride: ""

serviceAccount: "consul-backup-gcs"

vault:
  enabled: true
  image: vault
  tag: 1.3.2
  pullPolicy: IfNotPresent
  address: https://vault.service.consul:8200
  # PEM encoded CA used to issue Vault's Certificate
  ca: ""
  auth:
    path: "kubernetes"
    role: ""
  gcp:
    path: ""
  env: []

consul:
  address: consul-server.service.consul:8500

resources:
  vaultAgent: {}
  backup:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}

annotations:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}

gcs:
  bucket: ""
  prefix: "backup/consul/"
