apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
{{ include "cloudsql-proxy.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: {{ include "cloudsql-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
