# Default values for eks-container-insights.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccountName: fluentd

awsRegion: ""
clusterName: ""

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
