# Default values for eks-container-insights.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

priorityClassName: "system-node-critical"
serviceAccountName: fluentd

image: fluent/fluentd-kubernetes-daemonset
imageTag: v1.7.3-debian-cloudwatch-1.0

awsRegion: ""
clusterName: ""
s3Bucket: ""

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
