{{ $root := . }}
{{ range $i, $domain := $root.Values.certificates }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "cert-manager-aio.fullname" $root }}-cert-{{ $i }}
spec:
  secretName: {{ include "cert-manager-aio.fullname" $root }}-cert-{{ $i }}
  issuerRef:
    name: {{ include "cert-manager-aio.fullname" $root }}-issuer
    kind: ClusterIssuer
  renewBefore: {{ $domain.renew_before }}
  commonName: {{ $domain.common_name | quote }}
  dnsNames:
    {{- with $domain.san }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ end }}
