---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-aio.fullname" . }}-acme-solver-secret
type: Opaque
data:
  key.json: {{ required "Need to specify GCP Service Account key" .Values.clouddns.service_account_key | b64enc | quote }}
