{{- if or .Values.clouddns.service_account_key .Values.route53.aws_secret_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-aio.fullname" . }}-acme-solver-secret
type: Opaque
data:
{{- if eq .Values.acme_solver "clouddns" }}
  {{- if .Values.clouddns.service_account_key }}
  gcp-service-account-key.json: {{ .Values.clouddns.service_account_key | b64enc | quote }}
  {{- end }}
{{- else if eq .Values.acme_solver "route53" }}
  {{- if .Values.route53.aws_secret_access_key }}
  aws-secret-access-key: {{ .Values.route53.aws_secret_access_key | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
