---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-aio.fullname" . }}-acme-solver-secret
type: Opaque
data:
  gcp-service-account-key.json: {{ .Values.clouddns.service_account_key | b64enc | quote }}
  aws-secret-access-key: {{ .Values.route53.aws_secret_access_key | b64enc | quote }}
