# Default values for eks-container-insights.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

priorityClassName: "system-node-critical"
serviceAccount:
  name: fluentd
  annotations: {}

image: basisai/eks-container-insights
imageTag: v1.13.0

initImage: busybox
initImageTag: 1.32.0

awsRegion: ""
clusterName: ""

logToS3Bucket: false
s3Bucket: ""
# See https://github.com/fluent/fluent-plugin-s3/blob/master/docs/credentials.md
# Defaults to using Instance IAM
s3Credentials: |
  <instance_profile_credentials>
  </instance_profile_credentials>

# IRSA Example
# s3Credentials: |
#   <web_identity_credentials>
#     role_arn "#{ENV.fetch('AWS_ROLE_ARN')}"
#     web_identity_token_file "#{ENV.fetch('AWS_WEB_IDENTITY_TOKEN_FILE')}"
#     role_session_name "#{ENV.fetch('KUBERNETES_NODE_NAME')}-fluentd"
#   </web_identity_credentials>

additional_container_logs_filters: []
additional_systemd_logs_filters: []
additional_host_logs_filters: []

env: []
  # Use these variables if containerd runtime
  # - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
  #   value: "cri"
  # - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
  #   value: "%Y-%m-%dT%H:%M:%S.%N%:z"

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
