{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ambassador-consul-connector.serviceAccountName" . }}
  labels:
    {{- include "ambassador-consul-connector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-consul-connector.fullname" . }}
  labels:
    {{- include "ambassador-consul-connector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get", "list", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ambassador-consul-connector.fullname" . }}
  labels:
    {{- include "ambassador-consul-connector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ambassador-consul-connector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ambassador-consul-connector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
