apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: {{ include "ambassador-consul-connector.fullname" . }}
  labels:
    {{- include "ambassador-consul-connector.labels" . | nindent 4 }}
spec:
  {{- if .Values.ambassadorId }}
  ambassador_id: {{ .Values.ambassadorId }}
  {{- end }}
  hosts: []
  secret: {{ include "ambassador-consul-connector.fullname" . }}
