apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ include "ambassador-consul-connector.fullname" . }}
  labels:
    {{- include "ambassador-consul-connector.labels" . | nindent 4 }}
spec:
  {{- with .Values.ambassadorId }}
  ambassador_id:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hosts: []
  secret: {{ include "ambassador-consul-connector.fullname" . }}
